#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Step 1 - Daily data completeness.

Usable two ways:
  1) Standalone from the console: `python 1-completitud.py`. Edit the
     globals in section [A] and run.
  2) Imported by a future application (e.g. a local web app): call
     run_completeness(station=..., year=..., th_cov=...) directly. The
     globals below are only the *defaults* used by the console mode; the
     scientific calculation itself does not depend on them.
"""

import calendar
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

# ======================================================================
# [A] STUDY CONFIGURATION
# ======================================================================

# [A.1] Study case
STATION = "YELL"
YEAR = 2024
DOY_START = 1
DOY_END = 366  # 2024 is a leap year

# [A.2] Daily completeness threshold
# coverage = n_unique_minutes / 1440
TH_COV = 0.75

# [A.3] Console-mode plot behaviour. A future server should not pop a
# blocking matplotlib window on every run, so this stays a simple switch.
SHOW_PLOT = True

PLOT_TITLE = f"Daily data coverage — Station {STATION} ({YEAR})"


# ======================================================================
# [B] PARQUET COLUMNS USED (DO NOT TOUCH)
# ======================================================================
# Completeness only needs these columns from the Step 0 parquet:
#   - 01_sec_of_day
#   - 14_doy_utc
# The parquet is already single-station, no need to filter by station.
PARQUET_COLUMNS = ["01_sec_of_day", "14_doy_utc"]


# ======================================================================
# [C] PATH RESOLUTION
# ======================================================================
def resolve_paths(station: str, year: int, doy_start: int, doy_end: int, th_cov: float) -> dict:
    """
    Resolves every input/output path for a given station/year/DoY
    range/threshold, following the results/{STATION}/{YEAR}/... layout.

    Computed from the arguments received, not from the module-level
    globals, so run_completeness() behaves identically whether it is
    called from main() (console mode) or from a future caller with a
    different station/year.
    """
    parquet_path = (
        Path("results") / station / str(year) / "0_parquet"
        / f"0_{station}_{year}_observations.parquet"
    )
    global_inventory_csv = (
        Path("results") / "global" / str(year) / f"0_raw_file_inventory_{year}.csv"
    )

    results_dir = Path("results") / station / str(year) / "1_completeness"
    output_tag = f"{station}_{year}_DOY{doy_start}_{doy_end}_coverageTH{th_cov}"

    return {
        "parquet_path": parquet_path,
        "global_inventory_csv": global_inventory_csv,
        "results_dir": results_dir,
        "output_csv": results_dir / f"coverage_{output_tag}.csv",
        "output_png": results_dir / f"coverage_plot_{output_tag}.png",
    }


# ======================================================================
# [D] SCIENTIFIC CALCULATION (DO NOT TOUCH)
# ======================================================================
def missing_day_note(doy: int, df_inventory: pd.DataFrame) -> str:
    """
    Reason a DoY has no rows in the station's parquet, using the RAW file
    inventory generated by Step 0 instead of touching the RAW files again
    here. Same reasons the previous (RAW-reading) version of this script
    handled: missing_file, empty_file, no_data_for_station (plus
    read_error, if Step 0 recorded one).
    """
    if doy not in df_inventory.index:
        return "missing_file"

    inv = df_inventory.loc[doy]

    if not bool(inv["file_exists"]):
        return "missing_file"

    note = str(inv["note"])
    if note.startswith("read_error"):
        return note

    if not bool(inv["read_ok"]):
        return "empty_file"

    return "no_data_for_station"


def run_completeness(
    station: str = STATION,
    year: int = YEAR,
    doy_start: int = DOY_START,
    doy_end: int = DOY_END,
    th_cov: float = TH_COV,
) -> pd.DataFrame:
    """
    Computes daily completeness for one station/year/DoY range.

    Definition (unchanged from the validated version that read RAW
    directly, and from the version that later read the parquet one DoY
    at a time):
      minute = sec_of_day // 60
      n_minutes = # of unique minutes present (0..1440)
      coverage = n_minutes / 1440
      valid if coverage >= th_cov

    Pure calculation: reads its two inputs and returns a DataFrame. It
    does not print anything or write any file, so it can be reused as-is
    from main() (console mode) or from a future application.

    Raises FileNotFoundError with an explicit message if the Step 0
    parquet or the Step 0 global inventory are missing.
    """
    paths = resolve_paths(station, year, doy_start, doy_end, th_cov)
    parquet_path = paths["parquet_path"]
    global_inventory_csv = paths["global_inventory_csv"]

    if not parquet_path.exists():
        raise FileNotFoundError(
            f"Step 0 Parquet not found for station {station}: {parquet_path}\n"
            "Run 0-toParquet.py first."
        )

    if not global_inventory_csv.exists():
        raise FileNotFoundError(
            f"Step 0 global inventory not found: {global_inventory_csv}\n"
            "Run 0-toParquet.py first."
        )

    df_station = pd.read_parquet(parquet_path, columns=PARQUET_COLUMNS)
    df_inventory = pd.read_csv(global_inventory_csv).set_index("doy")

    # Unique minutes per DoY, computed once for the whole station in a
    # single vectorised pass, instead of filtering the full DataFrame
    # separately for each of the up-to-366 days. Same definition, same
    # numbers - only how the days are grouped changes.
    minute = (df_station["01_sec_of_day"] // 60).astype(int)
    n_minutes_by_doy = (
        df_station.assign(minute=minute)
        .groupby("14_doy_utc")["minute"]
        .nunique()
    )

    results = []

    for doy in range(doy_start, doy_end + 1):
        if doy not in n_minutes_by_doy.index:
            results.append({
                "DoY": doy,
                "n_minutes": 0,
                "coverage": 0.0,
                "status": "invalid",
                "note": missing_day_note(doy, df_inventory)
            })
            continue

        n_minutes = int(n_minutes_by_doy.loc[doy])
        coverage = n_minutes / 1440.0
        status = "valid" if coverage >= th_cov else "invalid"

        results.append({
            "DoY": doy,
            "n_minutes": n_minutes,
            "coverage": coverage,
            "status": status,
            "note": "ok"
        })

    return pd.DataFrame(results).sort_values("DoY").reset_index(drop=True)


# ======================================================================
# [E] SUMMARY STATISTICS (derived from run_completeness() output)
# ======================================================================
def compute_monthly_coverage(df_results: pd.DataFrame, year: int) -> pd.DataFrame:
    """
    Groups the per-day completeness table by local calendar month.

    Pure function: no prints, no file writes. Reused below by
    compute_completeness_summary() for best/worst month - written once so
    a future monthly view (heatmap/table) can reuse it too, instead of
    grouping by month a second time.

    Returns one row per month present in df_results: month, n_days,
    n_valid_days, valid_fraction.
    """
    df = df_results.copy()
    df["month"] = df["DoY"].apply(
        lambda doy: datetime.strptime(f"{year}-{int(doy):03d}", "%Y-%j").month
    )

    grouped = (
        df.groupby("month")
        .agg(
            n_days=("DoY", "size"),
            n_valid_days=("status", lambda s: int((s == "valid").sum())),
        )
        .reset_index()
    )
    grouped["valid_fraction"] = grouped["n_valid_days"] / grouped["n_days"]

    return grouped.sort_values("month").reset_index(drop=True)


def compute_completeness_summary(df_results: pd.DataFrame, year: int) -> dict:
    """
    Derives comparison-friendly summary statistics from the per-day
    completeness table already produced by run_completeness() - does not
    recompute completeness itself, only summarizes it.

    Pure function: no prints, no file writes. The only caller today is
    web_server.py::_handle_run_step1 - main() below computes its own
    simpler inline summary and never calls this function, so nothing
    about the console pipeline depends on this dict's shape.

    n_valid_days/n_total_days/coverage_pct are the same numbers already
    printed by main() - centralised here so console and any future
    caller (e.g. the local web server) read them from one place.

    n_invalid_zero_min/n_invalid_partial split the invalid days by
    whether the station has zero observed minutes that day (n_minutes==0,
    e.g. missing_file/empty_file/no_data_for_station/read_error - see
    missing_day_note()) or some observations that still fall short of
    th_cov (n_minutes>0). Deliberately not called "missing days" - a
    day with n_minutes==0 is not necessarily a missing file.

    longest_invalid_streak(s) are ALL runs of consecutive DoY with
    status != "valid" tied for the maximum length - a plain
    current_streak > longest comparison would silently keep only the
    first one (verified against real data: WHIT has two 5-day streaks,
    DoY 9-13 and 54-58; a strict-> comparison only ever reports the
    first). coverage_pct alone cannot distinguish "30 scattered invalid
    days" from "30 invalid days in a row" (the second is far more likely
    to be a real outage), and the DoY range is what makes a streak
    investigable (e.g. it may explain why a given month is the worst
    month - verified for UNSA: its 33-day streak is DoY 211-243, which
    covers nearly all of August, its worst month).

    best_months/worst_months are ALL months tied for the highest/lowest
    exact valid_fraction (compared before rounding - two months can be
    exactly equal, e.g. 31/31 and 30/30 both equal 1.0, without ever
    being "close after rounding" by coincidence). idxmax()/idxmin() would
    silently keep only the first tied month. Each entry carries its own
    valid-day count so "best"/"worst" carries a magnitude, not just a
    label - verified against real data: all 4 stations have at least one
    tied best or worst month this year.

    overall_coverage_pct is a DIFFERENT statistic from coverage_pct
    (Valid-day rate), deliberately kept alongside it rather than
    replacing it - the two answer different questions and are easy to
    conflate:
      coverage_pct        = % of days that individually clear th_cov
                             (a day either counts fully or not at all).
      overall_coverage_pct = % of all possible minutes in the DoY range
                             that were actually observed, across every
                             day including invalid/zero-minute ones -
                             100 * sum(n_minutes) / (n_total_days * 1440).
    Equivalent to coverage["coverage"].mean() * 100 given one row per
    DoY (guaranteed by run_completeness()), but computed from n_minutes
    directly so it stays traceable to the same formula regardless of how
    the coverage column itself is derived. Not a validity threshold -
    see the note built in updateThresholdNote() in the web UI.
    """
    n_total_days = int(len(df_results))
    n_valid_days = int((df_results["status"] == "valid").sum())
    n_invalid_days = n_total_days - n_valid_days
    coverage_pct = round(100.0 * n_valid_days / n_total_days, 2) if n_total_days else 0.0
    overall_coverage_pct = (
        round(100.0 * float(df_results["n_minutes"].sum()) / (n_total_days * 1440), 2)
        if n_total_days else 0.0
    )

    invalid_days = df_results[df_results["status"] != "valid"]
    n_invalid_zero_min = int((invalid_days["n_minutes"] == 0).sum())
    n_invalid_partial = int((invalid_days["n_minutes"] > 0).sum())

    ordered = df_results.sort_values("DoY")
    doys = ordered["DoY"].to_numpy()
    is_invalid = (ordered["status"] != "valid").to_numpy()

    streaks = []
    current_streak = 0
    current_start_doy = None
    for doy, invalid in zip(doys, is_invalid):
        if invalid:
            if current_streak == 0:
                current_start_doy = doy
            current_streak += 1
        else:
            if current_streak > 0:
                streaks.append((current_streak, int(current_start_doy), int(doy) - 1))
            current_streak = 0
    if current_streak > 0:
        streaks.append((current_streak, int(current_start_doy), int(doys[-1])))

    longest_invalid_streak = max((length for length, _, _ in streaks), default=0)
    longest_invalid_streaks = [
        {"start_doy": start, "end_doy": end}
        for length, start, end in streaks
        if length == longest_invalid_streak
    ]

    monthly = compute_monthly_coverage(df_results, year)
    max_fraction = monthly["valid_fraction"].max()
    min_fraction = monthly["valid_fraction"].min()

    def _month_entries(rows: pd.DataFrame) -> list[dict]:
        return [
            {
                "month": calendar.month_abbr[int(row["month"])],
                "n_valid_days": int(row["n_valid_days"]),
                "n_days": int(row["n_days"]),
                "pct": round(100.0 * float(row["valid_fraction"]), 1),
            }
            for _, row in rows.iterrows()
        ]

    best_months = _month_entries(monthly[monthly["valid_fraction"] == max_fraction])
    worst_months = _month_entries(monthly[monthly["valid_fraction"] == min_fraction])

    return {
        "n_valid_days": n_valid_days,
        "n_total_days": n_total_days,
        "n_invalid_days": n_invalid_days,
        "coverage_pct": coverage_pct,
        "overall_coverage_pct": overall_coverage_pct,
        "n_invalid_zero_min": n_invalid_zero_min,
        "n_invalid_partial": n_invalid_partial,
        "longest_invalid_streak": int(longest_invalid_streak),
        "longest_invalid_streaks": longest_invalid_streaks,
        "best_months": best_months,
        "worst_months": worst_months,
    }


# ======================================================================
# [F] OUTPUT HELPERS
# ======================================================================
def save_results_csv(df_results: pd.DataFrame, output_csv: Path) -> None:
    """Saves the daily completeness table to CSV."""
    df_results.to_csv(output_csv, index=False)
    print(f"\nResults saved to {output_csv}")


def create_coverage_plot(
    df_results: pd.DataFrame,
    th_cov: float,
    plot_title: str,
    output_png: Path,
    show_plot: bool = True,
) -> None:
    """
    Saves the annual coverage-vs-DoY plot. The PNG is always written;
    show_plot only controls whether an interactive window also opens
    (console mode wants this, a future local-server mode should not).
    """
    n_valid = int((df_results["status"] == "valid").sum())
    n_total = len(df_results)
    annual_valid_pct = 100.0 * n_valid / n_total if n_total > 0 else 0.0

    plt.figure(figsize=(10, 5))

    # Main series: daily coverage
    plt.plot(
        df_results["DoY"],
        df_results["coverage"],
        linestyle="-",
        label="Daily coverage"
    )

    # Threshold line (th_cov)
    plt.axhline(
        y=th_cov,
        linestyle="--",
        linewidth=1,
        label=f"Coverage threshold ({th_cov})"
    )

    plt.xlabel("Day of Year (DoY)")
    plt.ylabel("Daily coverage (n_minutes / 1440)")
    plt.title(plot_title)
    plt.grid(True, alpha=0.3)

    # Legend inside the plot
    plt.legend(loc="upper right")

    # Footer text - deliberately not "Annual valid days (coverage >= X)":
    # th_cov is a per-day threshold, annual_valid_pct is the share of days
    # that meet it - phrasing it as a single "annual >= X%" figure invites
    # reading the valid-day rate itself as if it had to clear th_cov, which
    # it does not (e.g. UNSA's 72.95% valid-day rate is not "below the 75%
    # threshold", it means 267/366 days individually cleared that per-day
    # threshold).
    footer_text = (
        f"Valid days: {n_valid}/{n_total} ({annual_valid_pct:.2f}%) — "
        f"daily threshold: coverage >= {th_cov * 100:.0f}%"
    )

    plt.figtext(
        0.5, 0.01,
        footer_text,
        ha="center",
        fontsize=9
    )

    plt.tight_layout()

    # Always save (traceability)
    plt.savefig(output_png, dpi=200)
    print(f"Plot saved to {output_png}")

    if show_plot:
        try:
            plt.show()
        except Exception as e:
            print(f"(INFO) Could not open plot window: {e}")

    plt.close()


# ======================================================================
# [G] MAIN PROGRAM (console mode)
# ======================================================================
def main() -> None:
    df_results = run_completeness(STATION, YEAR, DOY_START, DOY_END, TH_COV)

    print("\nFinal daily completeness table (first rows):")
    print(df_results.head(30))

    n_valid = int((df_results["status"] == "valid").sum())
    n_total = len(df_results)
    print(f"\nSummary: valid days = {n_valid} / {n_total}  (threshold={TH_COV})")

    annual_valid_pct = 100.0 * n_valid / n_total if n_total > 0 else 0.0
    print(f"Annual total coverage (days with coverage >= {TH_COV}): {annual_valid_pct:.2f}%")

    paths = resolve_paths(STATION, YEAR, DOY_START, DOY_END, TH_COV)
    paths["results_dir"].mkdir(parents=True, exist_ok=True)

    save_results_csv(df_results, paths["output_csv"])

    create_coverage_plot(
        df_results,
        th_cov=TH_COV,
        plot_title=PLOT_TITLE,
        output_png=paths["output_png"],
        show_plot=SHOW_PLOT,
    )


if __name__ == "__main__":
    main()
